version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -Lo /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Run hadolint on Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build and push Docker image for karsajobs-ui
          command: |
            # Build your karsajobs-ui application
            docker build -t ghcr.io/afrinaldipdg/karsajobs-ui:${CIRCLE_SHA1} .
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker push ghcr.io/afrinaldipdg/karsajobs-ui:${CIRCLE_SHA1}

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only:
                - karsajobs-ui
      - build-app-karsajobs-ui:
          filters:
            branches:
              only:
                - karsajobs-ui